openapi: 3.0.0
info:
  title: Postman Library API v2
  version: 1.0.0
servers:
  - url: https://library-api.postmanlabs.com
components:
  securitySchemes:
    apikeyAuth:
      type: http
      scheme: apikey
security:
  - apikeyAuth: []
paths:
  /books:
    get:
      tags:
        - default
      summary: get fiction books
      parameters:
        - name: genre
          in: query
          schema:
            type: string
          example: fiction
        - name: checkedOut
          in: query
          schema:
            type: boolean
          example: 'false'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: add books
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Bleach
                author: Tite Kubo
                genre: fiction
                yearPublished: 2001
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books/{id}:
    get:
      tags:
        - default
      summary: get books by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 9260f237-f853-4e60-a392-ee614ab95c0d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - default
      summary: checkout book
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                checkedOut: true
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 9260f237-f853-4e60-a392-ee614ab95c0d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete book
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 9260f237-f853-4e60-a392-ee614ab95c0d
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
